from __future__ import annotations

"""Regenerate sitemap.xml: evergreen pages + daily dated market pages.

Run after the daily page publisher, and weekly via cron as a safety net.
Usage: python3 sitemap_gen.py [--webroot /var/www/tradingai.in/html]
"""

import glob
import os
import sys
from datetime import datetime, timezone

BASE = "https://tradingai.in"
REPO_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

EVERGREEN = [
    ("", "daily", "1.0"),
    ("today/", "daily", "1.0"),
    ("market.html", "daily", "0.9"),
    ("indices/nifty.html", "daily", "0.9"),
    ("indices/banknifty.html", "daily", "0.9"),
    ("scanner.html", "daily", "0.8"),
    ("strategies.html", "weekly", "0.8"),
    ("strategy-builder.html", "weekly", "0.8"),
    ("strategies-guide.html", "weekly", "0.7"),
    ("history.html", "daily", "0.6"),
    ("stocks/top-large-cap.html", "daily", "0.8"),
    ("stocks/top-mid-small.html", "daily", "0.8"),
    ("stocks/top-performers.html", "daily", "0.8"),
    ("stocks/undervalued.html", "daily", "0.8"),
    ("stocks/52-week.html", "daily", "0.8"),
    ("etfs/top-etfs.html", "daily", "0.8"),
    ("sectors/top.html", "daily", "0.8"),
    ("queries/", "daily", "0.8"),
    ("global/markets.html", "daily", "0.7"),
    ("mutual-funds/", "daily", "0.8"),
    ("news/", "daily", "0.7"),
    ("options/pcr.html", "daily", "0.7"),
    ("indices/finnifty.html", "daily", "0.9"),
    ("indices/sensex.html", "daily", "0.9"),
    ("stock-options.html", "daily", "0.8"),
    ("learn/", "weekly", "0.7"),
    ("learn/option-chain.html", "monthly", "0.6"),
    ("learn/pcr.html", "monthly", "0.6"),
    ("learn/vwap.html", "monthly", "0.6"),
    ("learn/cpr.html", "monthly", "0.6"),
    ("learn/option-greeks.html", "monthly", "0.6"),
    ("tools/position-size.html", "monthly", "0.7"),
    ("about.html", "monthly", "0.3"),
    ("contact.html", "monthly", "0.3"),
    ("privacy.html", "monthly", "0.3"),
    ("terms.html", "monthly", "0.3"),
    ("disclaimer.html", "monthly", "0.3"),
    ("portfolio.html", "weekly", "0.6"),
    ("alerts.html", "weekly", "0.5"),
    ("tools/backtest.html", "weekly", "0.5"),
    ("etfs/holdings.html", "weekly", "0.5"),
]

DAILY_GLOBS = ("market/nifty-outlook-*.html", "market/nifty-close-*.html", "market/outlook-*.html")


def collect(repo_root: str = REPO_ROOT, extra_roots: list[str] | None = None) -> list[tuple[str, str, str, str]]:
    urls = [(path, freq, pri, "") for path, freq, pri in EVERGREEN]
    seen = {u[0] for u in urls}
    for root in [repo_root] + list(extra_roots or []):
        for pattern in DAILY_GLOBS:
            for fp in sorted(glob.glob(os.path.join(root, pattern))):
                rel = os.path.relpath(fp, root)
                if rel in seen:
                    continue
                seen.add(rel)
                try:
                    mtime = datetime.fromtimestamp(os.path.getmtime(fp), tz=timezone.utc).strftime("%Y-%m-%d")
                except Exception:
                    mtime = ""
                urls.append((rel, "monthly", "0.5", mtime))
    return urls


def render(urls: list[tuple[str, str, str, str]]) -> str:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             "<!-- Regenerated by backend/sitemap_gen.py. Run it after publishing daily pages. -->",
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for path, freq, pri, lastmod in urls:
        lines.append("  <url><loc>%s/%s</loc><changefreq>%s</changefreq><priority>%s</priority>%s</url>" % (
            BASE, path, freq, pri, f"<lastmod>{lastmod}</lastmod>" if lastmod else ""))
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def main() -> None:
    webroot = sys.argv[sys.argv.index("--webroot") + 1] if "--webroot" in sys.argv else None
    xml = render(collect(REPO_ROOT, [webroot] if webroot else None))
    with open(os.path.join(REPO_ROOT, "sitemap.xml"), "w") as f:
        f.write(xml)
    print(f"sitemap.xml written ({xml.count('<url>')} urls)")
    if webroot and os.path.isdir(webroot):
        with open(os.path.join(webroot, "sitemap.xml"), "w") as f:
            f.write(xml)
        import shutil
        for name in ("robots.txt",):
            src = os.path.join(REPO_ROOT, name)
            if os.path.exists(src):
                shutil.copy(src, os.path.join(webroot, name))
        print(f"synced to {webroot}")


if __name__ == "__main__":
    main()
