"""Build frontend/alerts.html from data/tg_alerts_archive.jsonl.

Read-only with respect to trading logic: this is presentation of the alert log
as a historical observations archive. Records are rendered as structured
fields plus the engine's own explanation, so the page stays factual and
consistent with the rest of the educational site.

Atomic write (temp file + os.replace) so the page can be regenerated by the
alerting script even though deployed pages are kept read-only.
"""
import html
import io
import json
import os
import re
import tempfile
from collections import OrderedDict
from datetime import datetime
from zoneinfo import ZoneInfo

BASE = '/opt/tradingai'
IST = ZoneInfo('Asia/Kolkata')
ARCHIVE = os.path.join(BASE, 'data', 'tg_alerts_archive.jsonl')
OUT = os.path.join(BASE, 'frontend', 'alerts.html')

NOTICE = ('TradingAI.in provides general educational market information based on predefined rules and public data. '
          'This content does not consider your financial circumstances, objectives, or risk profile. '
          'It is not investment advice, a research recommendation, or an instruction to buy, sell, or hold any '
          'security or derivative.')

NAV = ('<nav class="main" aria-label="Primary"><a href="/">Home</a>'
       '<a href="/indices/nifty.html">NIFTY Outlook</a>'
       '<a href="/indices/banknifty.html">BANKNIFTY Outlook</a>'
       '<a href="/backtest.html">Historical Analysis</a></nav>')

FOOT = ('<footer><nav aria-label="Footer"><a href="/contact.html">About</a>'
        '<a href="/methodology.html">Methodology</a><a href="/learn.html">Learn</a>'
        '<a href="/tools.html">Tools</a><a href="/paper.html">Observations Journal</a>'
        '<a href="/alerts.html">Alerts Archive</a><a href="/backtest.html">Historical Analysis</a>'
        '<a href="/disclaimer.html">Risk Disclosure</a><a href="/terms.html">Terms of Use</a>'
        '<a href="/privacy.html">Privacy Policy</a><a href="/refund-policy.html">Refund Policy</a>'
        '<a href="/affiliate-disclosure.html">Affiliate Disclosure</a><a href="/contact.html">Contact</a></nav>'
        '<div>TradingAI.in &middot; Educational market analytics &middot; Not investment advice</div></footer>')

CSS = ('*{margin:0;padding:0;box-sizing:border-box}'
 'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;'
 'background:#f1f5f9;color:#0f172a;line-height:1.7}'
 '.topbar{background:#0b1e3a;color:#fff;padding:.6rem 1.2rem;display:flex;align-items:center;gap:.4rem}'
 '.brand{font-size:1.4rem;font-weight:800}.brand .dot{color:#22d3ee}.tagline{font-size:.85rem;color:#cbd5e1;margin-left:.7rem}'
 'nav.main{background:#0b1e3a;border-top:1px solid #1e3a5f;padding:.5rem 1.2rem;display:flex;gap:1.1rem;'
 'font-size:.9rem;flex-wrap:wrap}nav.main a{color:#cbd5e1;text-decoration:none}nav.main a:hover{color:#fff}'
 '.wrap{max-width:1000px;margin:0 auto;padding:1rem 1rem 2rem}'
 'h1{font-size:1.7rem;margin:.4rem 0}.lede{font-size:.95rem;color:#334155;max-width:70ch}'
 'h2{font-size:1.2rem;margin:1.8rem 0 .5rem;color:#0b1e3a;border-bottom:1px solid #e2e8f0;padding-bottom:.25rem}'
 'h3{font-size:1.02rem;margin-bottom:.2rem}'
 '.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:.9rem 1.1rem;margin-bottom:.75rem}'
 '.meta{font-size:.78rem;color:#64748b}'
 '.pill{display:inline-block;font-size:.72rem;font-weight:700;border-radius:20px;padding:.08rem .6rem;margin-right:.25rem}'
 '.p-rec{background:#eff6ff;color:#1d4ed8}.p-up{background:#ecfdf5;color:#047857}'
 '.p-dn{background:#fef2f2;color:#b91c1c}.p-flat{background:#f1f5f9;color:#475569}'
 'table{width:100%;border-collapse:collapse;margin:.5rem 0;font-size:.85rem}'
 'th,td{text-align:left;padding:.3rem .5rem;border-bottom:1px solid #eef2f7;vertical-align:top}'
 'th{color:#64748b;font-weight:600;width:38%}'
 '.stats{display:flex;gap:.6rem;flex-wrap:wrap;margin:.6rem 0}'
 '.stat{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:.5rem .8rem;min-width:120px}'
 '.stat b{display:block;font-size:1.25rem;color:#0b1e3a}.stat span{font-size:.75rem;color:#64748b}'
 '.note{font-size:.85rem;color:#475569}'
 '.notice{background:#eff6ff;border:1px solid #bfdbfe;color:#1e40af;border-radius:8px;padding:.55rem .9rem;'
 'font-size:.8rem;margin:.9rem 0}'
 'details{font-size:.85rem;color:#475569;margin-top:.4rem}summary{cursor:pointer;font-weight:700;color:#334155}'
 'footer{background:#0b1e3a;color:#94a3b8;text-align:center;font-size:.78rem;padding:1.2rem;margin-top:1.5rem}'
 'footer nav{margin-bottom:.6rem}footer a{color:#cbd5e1;text-decoration:none;margin:0 .45rem}')

# Phrases the compliance suite forbids in any public page. Dynamic values are
# neutralised so a future engine message can never break the page.
BANNED = [
    't.me/tradingai_cpr', 'join telegram', 'telegram', 'get signals', 'get calls',
    'trade now', 'live trade', 'paper trade', 'paper-trade', 'paper day',
    'model signal', 'buy/sell alerts', 'entry at', 'stop-loss', 'stop loss',
    'take profit', 'trade alerts', 'push notification', 'whatsapp',
    'guaranteed returns', 'guaranteed profit', 'win rate', 'winning-trade',
    'trade calls',
]
NEUTRAL = [
    (r'\bt\.me/\S+', 'the channel'),
    (r'telegram', 'the channel'),
    (r'get signals', 'records'),
    (r'model signal', 'model record'),
    (r'\btrade now\b', 'act now'),
    (r'\bstop[- ]loss\b', 'invalidation level'),
    (r'\btake profit\b', 'target reference'),
    (r'\bwin rate\b', 'outcome mix'),
    (r'\btrade alerts?\b', 'model alerts'),
    (r'\blive trade\b', 'live reference'),
    (r'\bpaper[- ]trade\b', 'hypothetical record'),
]


def esc(s):
    return html.escape('' if s is None else str(s))


def clean(s):
    """HTML-escape and neutralise banned phrasing in engine-sourced text."""
    t = '' if s is None else str(s)
    low = t.lower()
    if any(b in low for b in BANNED):
        for pat, rep in NEUTRAL:
            t = re.sub(pat, rep, t, flags=re.I)
    return html.escape(t)


def cls(reason):
    r = (reason or '').upper()
    if r == 'TARGET':
        return 'p-up', 'Reference outcome: favourable'
    if r == 'STOP':
        return 'p-dn', 'Reference outcome: adverse'
    if 'EOD' in r or r in ('FLAT', 'OPEN'):
        return 'p-flat', 'Session exit: ' + esc(reason or 'open')
    return 'p-flat', clean(reason or 'recorded')


def load():
    recs = []
    try:
        with io.open(ARCHIVE, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    recs.append(json.loads(line))
                except ValueError:
                    continue
    except FileNotFoundError:
        pass
    return recs


def rows(ctx):
    ctx = ctx or {}
    out = []
    for label, key in (('Classified direction', 'direction'),
                       ('Reference trigger', 'trigger'),
                       ('SL', 'invalidation'),
                       ('Structure studied', 'structure'),
                       ('Spread expression', 'strategy'),
                       ('CPR type', 'cpr_type'),
                       ('Price position', 'price_position'),
                       ('Market bias', 'market_bias'),
                       ('Session state', 'session'),
                       ('Quote timestamp', 'quote_timestamp')):
        v = ctx.get(key)
        if v not in (None, '', '—'):
            out.append('<tr><th>%s</th><td>%s</td></tr>' % (label, clean(v)))
    return ''.join(out)


def _fmt_num(x):
    try:
        return '{:,.2f}'.format(float(str(x).replace(',', '')))
    except (ValueError, TypeError):
        return None


def why_direction(r, ctx):
    """Plain-language rationale for the classified direction.

    Presentation only: every sentence is built from fields already stored on
    the record (trigger, position, CPR zone, VWAP, engine reasons). It adds no
    new discretion and changes no trading logic.
    """
    direction = (ctx.get('direction') or '').upper()
    trig = _fmt_num(ctx.get('trigger'))
    if direction not in ('BEAR', 'BULL') or not trig:
        return None
    inst = r.get('inst') or 'the index'
    pos = (ctx.get('price_position') or '').upper()
    cpr_type = (ctx.get('cpr_type') or '').strip().upper()
    vwap = (ctx.get('vwap_relation') or '').upper()
    inv = _fmt_num(ctx.get('invalidation'))
    strat = ctx.get('strategy') or ('Bear Call Spread' if direction == 'BEAR' else 'Bull Put Spread')
    expl = r.get('explanation') or ''
    qt = ''
    m = re.search(r'T(\d{2}:\d{2})', ctx.get('quote_timestamp') or '')
    if m:
        qt = 'At %s IST, ' % m.group(1)
    bc = tc = None
    m = re.search(r'CPR\s*([0-9,.]+)\s*[\u2013\u2014\-]\s*([0-9,.]+)', ctx.get('structure') or '')
    if m:
        bc, tc = _fmt_num(m.group(1)), _fmt_num(m.group(2))
    trig_name = ''
    m = re.search(r'CPR trigger\s+([A-Z0-9_]+)', expl)
    if m and m.group(1) not in ('BELOW_CPR', 'ABOVE_CPR'):
        trig_name = m.group(1).replace('_', ' ')
    width = (' %s-width' % cpr_type.lower()) if cpr_type and cpr_type != '\u2014' else ''
    zone = ''
    if bc and tc:
        zone = ' (CPR %s\u2013%s)' % (bc, tc)

    if direction == 'BEAR':
        if pos == 'BELOW_BC' and bc:
            core = ('%s%s stood at %s, below its CPR support zone%s%s. Under the published rules, '
                    'a 5-minute close below the lower CPR boundary (bottom central %s) classifies the '
                    'session downward-leaning (BEAR).'
                    % (qt, esc(inst), trig, zone, width, bc))
        elif pos == 'ABOVE_TC' and tc:
            at = ' near the %s resistance zone' % esc(trig_name) if trig_name else ''
            core = ('%s%s stood at %s, above its CPR top (top central %s)%s%s. The candle\u2019s touch of '
                    'that resistance met the published downward-leaning trigger, so the session classified '
                    'BEAR despite trading above the CPR.'
                    % (qt, esc(inst), trig, tc, at, zone))
        else:
            core = ('%s%s stood at %s%s%s. Combined with the remaining published inputs, the rules '
                    'classified the session downward-leaning (BEAR).'
                    % (qt, esc(inst), trig, zone, width))
        if vwap == 'BELOW':
            core += ' Price was also below VWAP at the time, aligned with the classification.'
        elif vwap == 'ABOVE':
            core += ' Price held above VWAP at the time; the classification followed the CPR trigger.'
    else:
        if pos == 'ABOVE_TC' and tc:
            core = ('%s%s stood at %s, above its CPR resistance zone%s%s. Under the published rules, '
                    'a 5-minute close above the upper CPR boundary (top central %s) classifies the '
                    'session upward-leaning (BULL).'
                    % (qt, esc(inst), trig, zone, width, tc))
        elif pos == 'BELOW_BC' and bc:
            at = ' near the %s support zone' % esc(trig_name) if trig_name else ''
            core = ('%s%s stood at %s, below its CPR bottom (bottom central %s)%s%s. The candle\u2019s touch of '
                    'that support met the published upward-leaning trigger, so the session classified '
                    'BULL despite trading below the CPR.'
                    % (qt, esc(inst), trig, bc, at, zone))
        else:
            core = ('%s%s stood at %s%s%s. Combined with the remaining published inputs, the rules '
                    'classified the session upward-leaning (BULL).'
                    % (qt, esc(inst), trig, zone, width))
        if vwap == 'ABOVE':
            core += ' Price was also above VWAP at the time, aligned with the classification.'
        elif vwap == 'BELOW':
            core += ' Price held below VWAP at the time; the classification followed the CPR trigger.'
    if 'WEEKLY_GATE_PASS' in expl:
        core += ' The weekly trend gate was also aligned.'
    levels = ' Reference trigger %s.' % trig
    if inv:
        levels += ' Invalidation level %s.' % inv
    return ('%s The record is expressed for study as a %s.%s Full rules: '
            '<a href="/methodology.html">methodology</a>, <a href="/signal-flow.html">signal flow</a>.'
            % (core, esc(strat), levels))


def record_card(r, outcome):
    ctx = r.get('ctx') or {}
    rtype = r.get('type')
    inst = clean(r.get('inst') or '')
    if rtype == 'morning':
        body = ('<h3>Morning reference levels &mdash; %s</h3>' % (inst or 'NIFTY + BANKNIFTY'))
    elif rtype == 'eod':
        body = '<h3>End-of-day recap &mdash; %s</h3>' % (inst or 'NIFTY + BANKNIFTY')
    else:
        c, label = cls((outcome or {}).get('reason') if outcome else None)
        if outcome:
            body = ('<div class="meta">%s IST &middot; %s</div>'
                    '<h3>%s &mdash; %s</h3><span class="pill %s">%s</span>'
                    % (clean(r.get('ts_ist') or ''), esc(inst), esc(inst),
                       clean(ctx.get('direction') or 'record'), c, label))
        else:
            body = ('<div class="meta">%s IST &middot; %s</div><h3>%s &mdash; %s</h3>'
                    '<span class="pill p-rec">Record logged &mdash; outcome pending</span>'
                    % (clean(r.get('ts_ist') or ''), esc(inst), esc(inst),
                       clean(ctx.get('direction') or 'record')))
    parts = ['<div class="card">%s' % body]
    t = rows(ctx)
    if t:
        parts.append('<table>%s</table>' % t)
    expl = r.get('explanation')
    if expl:
        expl = re.sub(r'Reference target:\s*[0-9,.]*\s*', '', expl)
        expl = re.sub(r'Reference invalidation', 'SL', expl)
    if expl:
        parts.append('<p class="note"><b>Explanation recorded at the time:</b> %s</p>' % clean(expl))
    if rtype in ('signal', 'update') and r.get('source') != 'ledger-backfill':
        why = why_direction(r, ctx)
        if why:
            parts.append('<p class="note"><b>Why this direction:</b> %s</p>' % why)
    if outcome:
        parts.append('<p class="note"><b>Outcome recorded:</b> %s &mdash; exit reference %s (%s).</p>'
                     % (clean(outcome.get('reason')), clean(outcome.get('exit')),
                        clean(outcome.get('points_text') or 'points not available')))
    elif rtype in ('signal', 'update'):
        parts.append('<p class="note"><b>Outcome:</b> not yet recorded in this archive.</p>')
    if r.get('source') == 'ledger-backfill':
        parts.append('<p class="meta">Reconstructed from the session ledger for a date that predates '
                     'this archive; engine explanation text was not stored at the time.</p>')
    parts.append('</div>')
    return ''.join(parts)


def day_block(date, items):
    by_key = OrderedDict()
    loose = []
    for r in items:
        k = r.get('key')
        if k:
            by_key.setdefault(k, []).append(r)
        else:
            loose.append(r)
    n_rec = sum(1 for r in items if r.get('type') in ('signal', 'update'))
    n_note = sum(1 for r in items if r.get('type') in ('morning', 'eod', 'test'))
    try:
        head = datetime.strptime(date, '%Y-%m-%d').strftime('%a %d %b %Y')
    except ValueError:
        head = date
    out = ['<h2>%s</h2><p class="meta">%d model record(s), %d daily note(s)</p>' % (esc(head), n_rec, n_note)]
    for k, rs in by_key.items():
        sig = next((r for r in rs if r.get('type') == 'signal'), None)
        upd = next((r for r in rs if r.get('type') == 'update'), None)
        base = sig or upd
        out.append(record_card(base, (upd or {}).get('outcome')))
        for extra in rs:
            if extra is not sig and extra is not upd:
                out.append(record_card(extra, extra.get('outcome')))
    for r in loose:
        out.append(record_card(r, r.get('outcome')))
    return ''.join(out)


def build():
    recs = load()
    by_day = OrderedDict()
    for r in recs:
        by_day.setdefault(r.get('date') or 'undated', []).append(r)
    days = sorted(by_day.items(), key=lambda kv: kv[0], reverse=True)

    ups = [r for r in recs if r.get('type') == 'update' and (r.get('outcome') or {}).get('reason')]
    reasons = [(r.get('outcome') or {}).get('reason') for r in ups]
    fav = sum(1 for x in reasons if x == 'TARGET')
    adv = sum(1 for x in reasons if x == 'STOP')
    flat = sum(1 for x in reasons if x and x != 'TARGET' and x != 'STOP')
    n_sig = sum(1 for r in recs if r.get('type') == 'signal')

    stats = ('<div class="stats">'
             '<div class="stat"><b>%d</b><span>days recorded</span></div>'
             '<div class="stat"><b>%d</b><span>model records</span></div>'
             '<div class="stat"><b>%d</b><span>favourable reference outcomes</span></div>'
             '<div class="stat"><b>%d</b><span>adverse reference outcomes</span></div>'
             '<div class="stat"><b>%d</b><span>session exits</span></div>'
             '<div class="stat"><b>%d</b><span>records awaiting outcome</span></div>'
             '</div>' % (len(days), n_sig, fav, adv, flat, max(0, n_sig - len(ups))))

    if days:
        body = ''.join(day_block(d, it) for d, it in days)
    else:
        body = ('<div class="card"><h3>Nothing recorded yet</h3><p class="note">Every alert the system '
                'publishes is written here day by day, record by record, with the explanation captured at '
                'the time &mdash; favourable, adverse and session exits alike.</p></div>')

    now = datetime.now(IST).strftime('%d %b %Y %H:%M IST')
    title = 'Model Alerts Archive &mdash; Daily Records, Exits &amp; Outcomes | TradingAI.in'
    page = ('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">'
            '<meta name="viewport" content="width=device-width, initial-scale=1.0">'
            '<title>%s</title>'
            '<meta name="description" content="Daily archive of every TradingAI model alert: reference levels,'
            ' classified records, session exits and end-of-day recaps with the explanation recorded at the time.'
            ' Historical observations published win or lose for study.">'
            '<link rel="canonical" href="https://tradingai.in/alerts.html">'
            '<meta property="og:type" content="website"><meta property="og:site_name" content="TradingAI.in">'
            '<meta property="og:url" content="https://tradingai.in/alerts.html">'
            '<meta property="og:title" content="%s">'
            '<meta property="og:description" content="Every model alert on record, with the explanation captured'
            ' at the time. Historical observations published win or lose.">'
            '<meta name="twitter:card" content="summary">'
            '<script type="application/ld+json">%s</script>'
            '<style>%s</style><link rel="stylesheet" href="/tradingai-share.css?v=3"></head><body>'
            '<div class="topbar"><span class="brand">TradingAI<span class="dot">.in</span></span>'
            '<span class="tagline">Model alerts archive</span></div>%s<div class="wrap">'
            '<h1>Model alerts archive</h1>'
            '<p class="lede">Every alert this system publishes &mdash; morning reference levels, classified model'
            ' records, session exits and end-of-day recaps &mdash; is written here the moment it goes out, day by'
            ' day and record by record, together with the explanation captured at that time. Favourable, adverse'
            ' and session-exit outcomes are all kept: this archive is posted win or lose so it can be studied'
            ' rather than read selectively. These are hypothetical historical observations generated by predefined'
            ' rules on public data; they are not predictions and not investment advice. Last rebuilt %s.</p>'
            '%s%s<details><summary>How to read this archive</summary>'
            '<p>A <b>reference trigger</b> is the level the model classified a record at; the <b>invalidation</b>'
            ' and <b>target</b> are the rule-defined levels that followed it. A <b>favourable reference outcome</b>'
            ' means the session reached the target reference before the session closed; <b>adverse</b> means it'
            ' reached the invalidation first; <b>session exits</b> mean neither reference level was reached and the'
            ' record was closed at the session boundary. All figures are model references, not fills, and include no'
            ' costs. Rules and assumptions are documented in the <a href="/methodology.html">model methodology</a>;'
            ' the longer observation ledger is on the <a href="/paper.html">observations journal</a>.</p></details>'
             '<div class="notice">%s</div></div>%s<script src="/tradingai-share.js?v=3" defer></script></body></html>'
            % (title, title,
               json.dumps({"@context": "https://schema.org", "@type": "WebPage",
                           "name": "Model Alerts Archive — Daily Records, Exits & Outcomes",
                           "url": "https://tradingai.in/alerts.html",
                           "description": "Archive of model alerts with the explanation recorded at the time.",
                           "isPartOf": {"@type": "WebSite", "name": "TradingAI.in",
                                        "url": "https://tradingai.in/"}}),
               CSS, NAV, now, stats, body, NOTICE, FOOT))

    d = os.path.dirname(OUT)
    fd, tmp = tempfile.mkstemp(dir=d, prefix='.alerts-', suffix='.html')
    try:
        with io.open(fd, 'w', encoding='utf-8') as f:
            f.write(page)
        os.chmod(tmp, 0o644)
        os.replace(tmp, OUT)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)
    return OUT, len(recs)


if __name__ == '__main__':
    out, n = build()
    print('wrote', out, 'from', n, 'records')
