# -*- coding: utf-8 -*-
"""Unique editorial content blocks for each TradingAI page (AdSense thin-content fix)."""

CONTENT = {
"index.html": [
"TradingAI is a free, fully automatic market-intelligence service for the Indian stock market. This home page is the control room: from here you can reach the intraday outlook for NIFTY, BANKNIFTY, FINNIFTY and SENSEX, the broad-market dashboard, an equity scanner, options strategies, PCR and max-pain analysis, mutual fund snapshots, and a growing education library.",
"Every number on the site is computed from public Indian market data — index levels, option open interest, breadth, VWAP, RSI, ADX and the India VIX — by a rule-based pipeline. Those raw figures become a 'regime' (trending up, trending down, range-bound or volatile) and that regime drives the strategies you see on the index pages. No editorial opinion is involved: what you see is a reproducible reading of the data at that moment.",
"The portal cards below update through the trading day. During market hours they refresh on a fast cycle so the live prices visibly blink whenever a quote ticks up or down; after the close they settle to the day's final values. Because everything is computed server-side from stored candles, the same page works offline or shows historical context whenever the market feed is delayed.",
"We publish this for free and keep the methodology transparent. If a level, NAV or scanner row looks wrong, tell us via the contact page — data pulls from public feeds are occasionally corrected and we audit them regularly. For context on how we interpret indicators, see the Learn hub; for the legal boundaries of this information, see the disclaimer and terms. Nothing here is investment advice, and every decision to trade remains yours."
],
"market.html": [
"The market page is the full breadth-of-market dashboard. Where the home page shows highlights, this page lays out the complete picture: every index we track, real-time price and percent change, the advance/decline ratio across indices, and a granular card for each instrument with support-resistance zones, VWAP, RSI and the current regime.",
"A quick read of the grid tells a story in seconds: how many index cards are green or red, how far prices sit from their VWAP, and whether the day's move is a trending one (strong ADX) or a churn around a mean (weak ADX). The advance/decline strip at the top is an especially useful breadth check — it shows whether an index move is broad-based or narrow, which changes how much weight you should give to the move.",
"The data here is the same feed that powers the individual index pages, so the dashboard is your best 'at a glance' layer before you drill into NIFTY or BANKNIFTY for a structured outlook. During trading hours prices blink on every update so you can watch the day develop without reloading. After hours the page holds the close, and historical context stays available from the stored candles.",
"As with every page on TradingAI, the dashboard is generated from public market data by software and is provided for information and research. It is not advice to buy or sell anything. Use the page to understand the market's structure, then carry that understanding to your own decisions. For definitions of the indicators you see here, visit the Learn hub."
],
"history.html": [
"This page tracks how the published TradingAI 'signals' have actually performed. For each index, we lock in the outlook at the morning open and measure what happened by the close, recording the points won or lost had you followed the suggested direction. The result is an honest scoreboard: win rate, cumulative points, drawdown and profit factor, with every settled day listed below.",
"Keeping this scoreboard is the heart of the project. Anyone can generate a bullish or bearish call; what separates useful research from noise is whether the calls are measurable. By recording each day's expectation against its outcome — without editing out the losing days — we hold the analysis to a standard: does the regime model add information or does it resemble a coin flip? You can see the answer accumulating in real time.",
"There are several honest limitations to note. The scoreboard settles at the close and does not simulate real fills, slippage, commissions or the exact intraday timing you would face in a live trade. It also measures direction only — it is not the P&L of any specific strategy. Treat it as a transparent audit trail of the outlooks, not as a promise of performance.",
"Past results never guarantee future results, and the market can change character quickly. Use this page to judge whether the model is working for the conditions you trade in, then decide accordingly. If you believe a settlement is mis-recorded, get in touch — the ledger is public precisely so it can be checked."
],
"scanner.html": [
"The scanner page ranks the stocks TradingAI follows using a consistent, number-based framework rather than opinion. Each row shows the key indicators that drive our read of that stock — trend strength (ADX), momentum (RSI), position versus the day's VWAP, and the computed regime — so you can sweep the whole universe in seconds and shortlist names that fit your style.",
"A good scan session asks specific questions. Are there many names pressing to new intraday highs with rising momentum (a healthy broad tape), or is breadth thin and the strength concentrated in a handful of large-caps? Which stocks are trending cleanly (high ADX) versus chopping sideways where an entry carries more noise? Keeping those questions in mind makes the scanner a triage tool instead of a noise generator.",
"You can filter the list live by regime, sector or signal type. Clicking a symbol takes you to that stock's detailed page with its support and resistance, VWAP and full technical picture, so the scanner is designed as the 'wide net' that feeds deeper single-stock analysis.",
"As always, the output is computed automatically from public market data and is for research, not a recommendation. Scans describe what the data shows right now; they cannot know your risk tolerance or horizon. Verify levels before trading and treat the rows as questions worth investigating, not as instructions."
],
"stock.html": [
"This is the single-stock research page. It pulls together the live quote, the computed technical indicators (VWAP, RSI, ADX, support and resistance), the prevailing regime, and a plain-language outlook for the symbol you asked for. It is the same engine that powers the scanner and index pages, focused on one name.",
"The support and resistance zones are derived from recent price action and are intended as decision aids, not guaranteed levels. VWAP shows where the day's institutional average price sits — companies often respect it intraday. RSI tells you whether a stock is stretched after a move, and ADX tells you whether the move has genuine directional strength or is just oscillation. Reading these together gives a structured way to assess a stock instead of reacting to the last tick.",
"Every stock page also links to the broader tools: the scanner to find names, the strategies page for the approach, and trading history to judge whether the published views are working. The education hub explains each indicator in plain language if you want to go deeper.",
"The page is generated automatically from public market data. It is research context, not personalised advice and not a recommendation. Prices flicker through trading hours and settle at the close. Always verify current data with your broker and make your own risk decisions."
],
"stock-options.html": [
"Stock options on Indian equities are physically settled and behave differently from index options — this page is built around those differences. It shows the optionable stocks TradingAI tracks, their expiry calendars and the current quote, so you can plan around the realities of stock options: monthly expiries, broader strike spacing and mandatory delivery on assignment.",
"Understanding physical settlement matters before you trade a single contract. If an exercised option is not covered, you could face delivery obligations or margin implications far beyond what index options imply. That is why this page links every symbol back to its detailed research page and to the strategy builder, and why the education library explains the mechanics of exercise and assignment rather than only the payoff diagrams.",
"For traders who understand physical settlement, stock options open strategies that index options cannot — pairs, covered writes and expiry-based plays on single names. The page is a starting point to screen which stocks have active option chains and enough liquidity to make a strategy viable, then to size the position in the calculator below.",
"Options are high-risk instruments and stock options add delivery risk on top. This page and the site in general provide research and education only; they are not recommendations to buy or sell any option. Confirm margins, lot sizes and settlement rules with your broker before placing any order."
],
"strategies-guide.html": [
"This guide is the plain-English reference for every options strategy TradingAI can assign. For each strategy you get the intended outlook, the exact leg structure, maximum profit, maximum loss, the breakeven calculation, and the market condition it suits. It is the dictionary the rest of the site relies on when an index page says 'Bull Put Spread' or 'Iron Condor'.",
"Reading the guide before the strategy pages saves a lot of confusion, because the name alone does not tell you the risk. A 'condor' is usually low-risk but caps your profit; a 'straddle' can profit from a big move either way but bleeds value if the index sits still. Knowing which condition each strategy is designed for lets you compare what the site recommends against what you actually believe the market will do.",
"The last row — NO TRADE — is every bit as important as the rest. 'Conflicting signals, stale data, or extreme VIX' is a legitimate conclusion, because preserving capital is itself a position. A tool that never said 'no trade' would be telling you something false about the quality of the intraday data.",
"This material is educational. Options involve substantial risk and possible loss of the whole premium (and more, for short legs). No structure shown here guarantees a profit. Use the guide to understand the mechanics, then make your own assessment of the market and your situation."
],
"strategies.html": [
"Strategies is where TradingAI translates a market read into a structured options plan. Based on the computed regime for each index — trending, range-bound or volatile — the page selects an appropriate options structure (for example a vertical spread for a moderate trend, or a defined-risk premium-selling approach when volatility is high), shows the legs, and links each idea to the payoff builder.",
"The logic is deliberately conservative. The system prefers defined-risk structures over naked premium selling, and it refuses to suggest a trade at all when the signals disagree. That is by design: in an automated service, the costliest failure is suggesting a precise trade on top of ambiguous data. When the page says NO TRADE, it is protecting you from an unreliable read, not being shy.",
"Each strategy row links to the guide so you can read the mechanics of the structure and to the builder so you can see the payoff profile at any strike you choose. Studying why a structure fits a regime — and when it breaks — is the fastest way to make these tools your own rather than taking them at face value.",
"Strategies are generated from public end-of-day and intraday data and may be delayed by the feed. They are research illustrations, not recommendations and not personalised advice. Options risk losing the entire premium and more. Verify premiums, margins and lot sizes with your broker before acting."
],
"strategy-builder.html": [
"The strategy builder is an interactive calculator that shows you the payoff of an options position before you commit to it. You pick a symbol, choose a strategy (or build legs yourself), and the builder computes profit and loss against the index price using the nearest available strike table. It is the sandbox where 'what if this happens?' questions get answered numerically.",
"Playing with the builder is the fastest way to understand options risk. Push the curve: what happens to a bull call spread if the index falls 500 points? Where does an iron condor start losing? How fast does a long straddle decay if nothing happens? Because the payoff lines are drawn from your chosen strikes, the tool makes the abstract math of options tangible.",
"The builder uses live index levels to build the strike table and approximate premiums, which is a planning aid rather than a quote. Real order premiums fill at your broker and depend on bid-ask, volatility and time to expiry, so the rupee values here are directional estimates — always confirm the actual premium when you place the order.",
"No calculator can promise a real-world outcome. Options carry substantial and often uncapped risk, especially short legs, and payoff charts assume no slippage or early assignment. Use the builder to understand the shape of a position's risk; take responsibility for the real trade yourself."
],
"indices/nifty.html": [
"This page is the full TradingAI read on the NIFTY 50. Everything on it — the intraday chart, key S/R levels, India VIX, PUT-CALL ratio, max pain, the AI outlook and the recommended strategy — comes from the same automatic pipeline: publicly available NSE data in, structured analysis out. It is the flagship example of how the platform thinks.",
"The sections reinforce one another. The candlestick chart shows where price has actually traded and how far it has drifted from the open. The key levels turn that drift into R1, R2, S1 and S2 levels you can plan around. VIX tells you whether the market is priced for calm or for a shock. And the options box summarises where the big money sits: heavy open interest and the max-pain strike offer a view of what the expiry might 'want' to do. Reading the chart, levels and options together is more informative than any single number.",
"During market hours the page refreshes on a fast cycle, and price, levels and PCR figures are recomputed from the live feed. The strategy line labels the optical trade the model would consider under the current regime — and it will honestly say NO TRADE when signals conflict.",
"This is automated research, not advice, and NIFTY derivatives risk losing the entire premium and more. Max-pain and PCR are end-of-day constructs and should not be read as guarantees. Verify data with your broker and decide for yourself."
],
"indices/banknifty.html": [
"Bank NIFTY is the market's favourite indicator of sentiment in the banking and financial sector, and this page applies the full TradingAI engine to it: intraday candles, pivot levels, VIX context, options intelligence and a structured outlook. Because banking stocks dominate index moves, Bank NIFTY often moves faster and with wider ranges than NIFTY itself.",
"The concepts are the same ones you see on the NIFTY page — support and resistance from price action, VWAP as the institutional average, RSI and ADX for momentum and trend, PCR and max pain from open interest — but they answer a different question: is the financial sector the source of the day's strength or weakness? When Bank NIFTY diverges from NIFTY, the divergence itself is information about where capital is rotating.",
"Because Bank NIFTY strikes are spaced wider (100 points) and your lot size differs, the strategies shown here can need higher margins than the equivalent NIFTY trade. The strategy builder lets you price the exact position before you place it, and the indicator definitions live in the Learn hub.",
"Bank NIFTY options are highly volatile and can lose the entire premium quickly. The analysis is generated automatically from public data for research; it is not a recommendation, and option spread, slippage and gap risk can change outcomes materially from the paper model."
],
"indices/finnifty.html": [
"FINNIFTY — the NIFTY Financial Services Index — captures banks, insurers and other financials with a different weighting than Bank NIFTY, and this page gives it the full TradingAI treatment: live candles, levels, volatility context, PCR and max pain, and a regime-based outlook.",
"Wealth managers and financials outside the pure banking names are included here, so FINNIFTY is often a cleaner lens on the 'financials complex' than Bank NIFTY alone. When the two indices diverge it usually points to rotation between banks and non-bank financials — read that spread alongside this page's breadth and options data for a fuller picture of sector strength.",
"FINNIFTY trades a tighter, more liquid option chain and is increasingly popular for intraday traders. The same disciplines apply: check the chart for trend, RSI for stretch, ADX for strength, and the options box for where open interest is concentrated. The strategy links open the builder so you can examine a payoff before considering it.",
"All output here is automated and derived from public market data; it is research context and not advice. FINNIFTY options carry the same premium-loss and gap risks as any derivatives. Always verify levels and margins with your broker before trading."
],
"indices/sensex.html": [
"SENSEX is India's bellwether index of the BSE's 30 largest, most established companies, and this page applies the TradingAI engine to it. The intraday chart, S/R levels, VIX, options perception and strategy line are all produced from public market data by the same pipeline used for the other indices.",
"SENSEX is dominated by large, liquid blue-chips, so it tends to be a slightly steadier tell on institutional positioning than the broader NIFTY. When you read it alongside the other index pages you can separate a market-wide move (all indices behaving alike) from a selective one (only some spaces participating) — which is often the most useful thing to know on a given day.",
"The page includes the same options intelligence as the other index pages. Because only a fraction of BSE stocks have active options and SENSEX derivatives trade less than NIFTY's, the PCR and max-pain figures here should be read with that liquidity context in mind.",
"SENSEX is not an investible product in itself; you trade it via futures, options or ETFs. The analysis is generated automatically for research and information and is not investment advice. Data can be delayed or erroneous — verify with your broker and make your own decisions."
],
"today/index.html": [
"The Today page is a fast summary of where the market sits right now: the closing snapshot of the major indices, today's key events, and links into the deeper research layers of the site. It is built to answer one question quickly — 'what happened today, and what should I look at next?'",
"The page emphasises the session's result because context matters: a 0.3% NIFTY move on a low-volatility day is a different story than the same move on a VIX spike. The index strips update through the trading day and settle at the close, and each strip links to the full outlook page for that instrument.",
"Use Today as a daily habit: glance at the closes, note how breadth behaved, then spend your real attention on the index pages that matter to the positions you hold or the sectors you trade. Consistent daily reading builds a mental model of the market's character that static articles cannot.",
"The content is automatically assembled from public market data for information and research. It is not advice, and a day's headline move is never a reason by itself to trade. Verify data before acting."
],
"etfs/top-etfs.html": [
"This page ranks the ETFs TradingAI tracks by live performance. ETFs open a cheap, liquid way to participate in a market theme — index, sector, gold or international equity — and this listing shows their movement at a glance so you can compare assets with very different return profiles side by side.",
"A useful habit is to compare an index ETF's move with the index page for the same benchmark. If the ETF is drifting away from its NAV or its underlying, liquidity and tracking error deserve a look. The same applies to gold or international ETFs, where currency and global hours add another layer.",
"Every row links to the symbol's research page so you can read the technical context behind the price, and the Learn hub explains how ETFs, premium/discount and tracking error work for investors new to these products.",
"ETF prices here come from public feeds and can be delayed or approximate. Nothing on this page is a recommendation to buy or sell a fund. Compare NAV, expense ratio, and liquidity on the AMC's own site before investing — educational context only."
],
"global/markets.html": [
"Global markets sets India in its world context. It tracks major international indices and the currencies and commodities that matter most to Indian investors — the dollar, crude oil, gold, and key equity benchmarks — so you can see the environment in which Indian markets are trading.",
"Indian markets are not an island. Crude oil moves affect our trade balance, inflation and the rupee; the dollar and US yields drive capital flows into and out of emerging markets; and a risk-off night in New York routinely shows up in our morning gap. Reading this page alongside the domestic dashboard tells you whether India's move is home-grown or imported.",
"Data here arrives from public sources and is inherently delayed (typically ~15 minutes plus exchange holidays in different time zones), so treat it as context, not as a tick-by-tick feed. Use it to frame the day, then keep your decisions in the instruments you actually trade.",
"Global data is research and information only, never advice. Cross-border markets carry currency, time-zone and liquidity risks of their own. Verify rates from a bank or broker screen before any decision."
],
"learn/index.html": [
"The Learn hub is TradingAI's education library — plain-English explanations of the indicators and concepts used across the site. Every page in the hub is written to be understood without a finance background: what the number means, where it comes from, and how to use it in practice.",
"Reading the hub makes the rest of the site far more valuable. Terms like VWAP, RSI, ADX, CPR, PCR, max pain and option greeks appear constantly on the market pages; once you understand each one you can interpret a dashboard row or a strategy suggestion critically instead of treating it as a black box. Education is the antidote to taking automated output at face value.",
"Each lesson is short and practical and links to the tool where the concept is used, so you can learn a concept and immediately see it in real data. Start with whichever concept confuses you most — that is the one returning the most value to your trading decisions.",
"The hub is educational content, not financial advice. Understanding an indicator never means the market will obey it. Use what you learn to frame your own research and judgments, and verify everything with real market data before acting."
],
"learn/cpr.html": [
"The Central Pivot Range (CPR) lesson explains a straightforward but powerful frame for the trading day: the pivot, the top central (TC) and bottom central (BC) lines that many institutional and algorithmic desks watch. When price sits inside the CPR, the market is often still deciding; breaking out of it tends to signal intent.",
"This article covers how the three CPR levels are calculated from the previous day's high, low and close, how to read 'narrow' versus 'wide' CPR days, and why a narrow range frequently precedes a larger move. It also shows how TradingAI uses CPR in context with VWAP and yesterday's levels rather than as a standalone oracle.",
"Pair the lesson with the index pages to see CPR applied to today's real data, and with the VWAP lesson for the complementary concept of the institutional average price. Together they describe a day in terms most discretionary intraday traders use naturally.",
"This is educational material. CPR levels are probabilities, not promises — breakouts fail, and fakeouts are common. Understand the concept, watch it in live markets, and always manage risk as if the level will be tested twice."
],
"learn/pcr.html": [
"The Put-Call Ratio (PCR) lesson explains how derivative positioning can be read from options open interest. A higher PCR means puts are being accumulated relative to calls — often interpreted as caution — while a lower PCR points to call-heavy positioning. TradingAI computes PCR from the end-of-day options bhavcopy and shows it on the PCR page and index dashboards.",
"The article carefully explains the two common uses of PCR — as a contrarian sentiment gauge (extreme readings) and as a technical backdrop (open interest concentration) — and warns against a simple 'never call bottoms' rule. It also explains why the ratio varies by expiry and by instrument and why reading it involves the full option chain, not one number.",
"Combine the lesson with the live PCR page, which shows the ratio, max pain, and top open-interest strikes for NIFTY, BANKNIFTY and FINNIFTY, and with the option-chain lesson to understand the layout of puts and calls at each strike.",
"This is education, not tradeable advice. PCR is measured on close-of-day data, can lag the market, and is one input among many. Learn the concept, watch how it behaves across regimes, and never trade a single indicator."
]
,
"learn/option-chain.html": [
"The option chain lesson explains how to read a market maker's board of calls and puts — strike by strike, with open interest, volume and premiums — and how the shape of that board reflects what traders expect. It is the foundation that makes concepts like PCR, max pain and open-interest concentration meaningful.",
"You will learn what the columns mean, how to identify where the heaviest positions sit relative to the current price, what a 'wall' of call strikes does to an index near expiry, and why open interest can be more informative than volume for spotting positioning. The lesson uses real chain layouts so the pattern stays familiar when you encounter it on the site's PCR and options pages.",
"The natural follow-ons are the PCR lesson (which summarises chain positioning into one ratio), the max-pain discussion, and the option-greeks page, because position sizes are only part of the story — how those positions react to price changes (greeks) determines the real behaviour near expiry.",
"This is educational content. An option chain is a snapshot of traded positions, not a forecast; heavy OI can unwind unexpectedly near expiry. Use it to understand the landscape, then make your own decisions with real data and proper risk awareness."
],
"learn/option-greeks.html": [
"The option greeks lesson unpacks the five letters that describe how an option's price responds to the world: delta (move with the underlying), gamma (how fast delta changes), theta (time decay), vega (response to volatility) and rho (response to rates). For anyone trading options on the indices this page is the vocabulary of risk.",
"The article explains each greek intuitively and with small numeric examples: why a deep-in-the-money call has delta near 1, why long options bleed theta daily, and why vega makes options expensive when VIX is high and cheap when it is low. It connects the greeks back to the strategies the site suggests — for example, why time decay plays favour range-bound regimes.",
"If you trade from TradingAI's strategy suggestions, understanding greeks lets you see *why* a structure was chosen and where its risk really lives, and to judge whether that matches your view better or worse than the model's. The strategy builder lets you observe these effects on a real payoff before you trade.",
"This is educational material, not advice. Greeks are model-based estimates that change continuously. Options, especially short or multi-leg positions, carry substantial and often complex risk; learn the mechanics and then trade only what you fully understand."
],
"learn/vwap.html": [
"The VWAP lesson explains Volume-Weighted Average Price — the average price at which an instrument has traded that day, weighted by volume. Institutions and algorithmic desks use VWAP as a benchmark, which makes it one of the most respected intraday reference levels for Indian traders.",
"You will learn how VWAP is constructed, why the day's first trades carry heavy weight, how to read price relative to VWAP (above is often considered 'bought', below 'sold' relative to the session's average cost), and how authorities and desks flock to it during ranging sessions. The article contrasts VWAP with simple day-pivots and CPR to show when each is useful.",
"See VWAP in action on any stock or index page — it is shown against support and resistance and used in the 'why' chips that explain each outlook. Pair the lesson with the CPR page to build a complete picture of the day's frame.",
"This is education, not advice. VWAP is a reference the market often respects but never obeys, and it resets daily. Learn it, watch it, and keep it as one input among several in your own decision process."
],
"mutual-funds/index.html": [
"TradingAI now covers mutual funds as well as equities — this page shows the best direct-growth scheme in each major category based on the latest NAV returns, alongside the number of schemes collected into our database. We use AMFI's published NAVs and deliberately prefer Direct plans, whose lower expense ratios matter enormously to long-term compounding.",
"Reading fund rankings responsibly means understanding the metric. We rank by recent returns so you can see which categories have momentum, but winners rotate — a top-1Y fund is not automatically a great 3Y or 10Y fund. Category first, scheme second: decide which category fits your horizon and risk, then compare schemes within it on returns, standard deviation, expense ratio and fund-manager consistency.",
"Direct plans and regular plans differ mainly in the distribution commission built into the regular plan's expense ratio. For the same fund, direct NAVs are typically a percentage lower in cost, which compounds into meaningfully higher long-term returns. That is why we surface direct-growth options by default.",
"This page is informational, built from public AMFI data that can lag or contain errors. It is not advice to buy or sell any fund, and past returns never guarantee future performance. Always verify the current NAV, expense ratio and exit loads with the AMC or AMFI before investing."
],
"news/index.html": [
"The news page gathers today's market headlines, pre-market cues and corporate actions from public sources and organises them around the symbols and themes TradingAI tracks. It is the 'what moved, and why' layer that turns raw price data into narrative context.",
"Reading markets well means triangulating the numbers with the news. A big NIFTY gap usually has a catalyst in the morning cues; a stock pinned at its day high often connects to an announcement in the news list. Keep the market dashboard and an index page open alongside this feed so price behaviour and headlines speak to each other.",
"Corporate actions matter mechanically: dividends, splits, buybacks and rights issues change price series and can distort technical signals. We surface these so you can adjust your read of a chart instead of being surprised by an ex-date gap. Our data-quality and regime pages explain how these events are handled in the pipelines.",
"Headlines open to external sources under their own terms, and we do not vouch for their accuracy. The page aggregates public information for research; it is not advice, and reacting to a headline alone is rarely a sound strategy. Verify facts before acting."
],
"options/pcr.html": [
"The PCR page is TradingAI's options-sentiment workbench. It computes the Put-Call Ratio, max-pain strike, and the highest open-interest strikes for NIFTY, BANKNIFTY and FINNIFTY from the official end-of-day options bhavcopy, and lets you drill into any expiry with an interactive chain view. It is the deepest derivative view on the site.",
"Three figures matter here. The PCR tells you whether puts or calls dominate positioning for that expiry. Max pain is the strike at which the most option premium would expire worthless — the level the market is often 'pushed' towards near settlement. And the top-OI strikes show where the biggest option walls sit, which frequently act as magnets or barriers around these levels.",
"Because the data is end-of-day, this is context for the close and the upcoming expiry, not an intraday feed. The page's expiry selector defaults to the current contract and any of several expiries can be examined — which is valuable because max-pain behaves differently for weekly versus monthly expiries. Pair it with the index pages to see price action against the levels it reveals.",
"PCR and max pain come from public data and are probabilities, not certainties; heavy positions can unwind unexpectedly near expiry. Nothing on this page recommends a trade. Use it to understand positioning, then decide within your own risk limits."
],
"queries/index.html": [
"The Queries hub is a set of live, askable market questions — top performers, biggest gainers and losers, sector strength, unusual volume, and other custom screens that would normally require a dedicated deal. Each query is computed from current market data on every visit, so the answers are the market's, not a static list.",
"Using queries well is about asking sharper questions. Instead of 'which stocks are rising', ask 'which stocks are rising *on volume* in a failing tape?' or 'which sectors are leading while the index drifts?'. The hub's filters let you combine conditions so the output matches a thesis rather than merely confirming one.",
"Each query card links back to the scanner and to individual stock pages, so a good answer becomes the start of deeper research rather than the end of it. Queries also complement the news page: unusual volume often precedes an announcement, and the two layers together frame the day.",
"Queries are computed automatically from public feeds and can be delayed; a ranking is a moment-in-time snapshot, never a forecast. They are tools for research, not reasons to trade. Verify any name you act on with current data and your own analysis."
],
"sectors/top.html": [
"The Sectors page ranks market sectors using proxy baskets of the stocks TradingAI tracks, so you can see where strength and weakness are concentrated across Banking, IT, Pharma, Energy, Metals, FMCG, Auto and more. It answers 'which part of the market is working today?' — the essential breadth question behind any index move.",
"Sector leadership rotates. Early in a market rally cyclicals and financials often lead; defensives and FMCG tend to shine in risk-off sessions; IT moves on global tech sentiment and the rupee. Watching which sector is leading — rather than only watching the index level — tells you the character of the current move and how durable it may be.",
"The baskets are approximate proxies we maintain for the stocks we follow, so a sector can only be as accurate as its constituents. Pair the sector view with the scanner to confirm individual names and with the news feed to understand any catalyst behind the rotation.",
"Proxy reflects our coverage, and coverage can lag the exchange's official indices. The page is automatically built from public data for research, not advice. Use it to understand the day's leadership, then investigate the specific names yourself."
],
"stocks/52-week.html": [
"The 52-week page surfaces which tracked stocks are pressing near their one-year highs or lows — one of the most revealing long-chart relationships a trader can scan. It compares the latest close against the highest high and lowest low of the past year and flags names within a few percent of either extreme.",
"Breakouts toward new highs with increasing volume can confirm institutional interest; stocks hugging their lows may be cheap or may be value traps. Reading both lists together shows you the market's internal momentum — many names near highs on rising tape is healthy, while a broad cluster near lows warrants caution.",
"The page is computed from a year of stored daily candles per stock, so the extremes are exact up to your data's depth. Every row links to the stock's research page, to the scanner for momentum checks, and the Learn hub explains how support and resistance form on long time frames.",
"This is automatically generated research from public market data, not a tip list. 'Near the 52-week high' is information, not a buy signal — trend-following works less well in range-bound regimes. Always verify levels and do your own diligence before trading."
],
"stocks/reliance.html": [
"RELIANCE is one of the most-watched names on Indian screens, and this page is its full TradingAI treatment: live quote, technical indicators (VWAP, RSI, ADX), support and resistance, the computed regime and a plain-language outlook, generated automatically from public market data.",
"Reliance spans energy, retail, telecom and refining, so its chart often moves on unrelated news streams inside the conglomerate. That is why this page pairs the technical read with the news feed and corporate-actions list — a breakout supported by a concrete catalyst is more meaningful than one that arrives unannounced.",
"Because the stock's liquidity is deep, the technical levels here tend to be respected by brief traders; treat the S/R zones as decision aids rather than promises. The page links to the scanner to compare RELIANCE against the market, and to the strategies and builder pages for options ideas with defined risk.",
"The page is generated automatically for research and information. S/R, VWAP and RSI are probabilities, not guarantees, and the stock can gap through a level on news. Never trade on this page alone; verify live data with your broker and consider your own risks."
],
"stocks/top-large-cap.html": [
"Top Large Cap ranks the largest, most liquid stocks TradingAI follows by live performance, so you get an instant read on how the heavyweight names — the ones that steer NIFTY — are behaving today.",
"Large-caps drive index moves, so this listing is effectively the market's engine room. When the top of the list is broadly green on strong breadth, index upside tends to be more durable; when a few names carry the whole index while most drift, the move is fragile. Reading the performance split tells you whether strength is real or concentrated.",
"Each row links to the full research page for that stock and to the scanner for the momentum context, so a strong (or weak) performer becomes a starting point for investigation rather than a one-line number. The Learn hub explains how to read performance rankings with volume and relative strength.",
"The list is computed from public market data at the time you load it — a snapshot with typical feed delays, not a recommendation. Large-caps are 'safer' than small-caps but they are still equities carrying real risk. Verify levels and do your own diligence before trading."
],
"stocks/top-mid-small.html": [
"Top Mid/Small ranks the middle- and small-cap names TradingAI tracks by live performance. These stocks can move with much larger ranges than large-caps, so the list is a fast way to see where speculative energy is flowing on a given day.",
"Mid- and small-cap strength is a classic tell of risk appetite. When money rotates from large-caps into mids and smalls on good breadth, traders call it a 'risk-on' tape; when the list is quiet and red while large-caps hold, it usually signals caution. Watching this rotation is a useful independent gauge alongside the index pages.",
"Because these names are thinner, their quotes can be more volatile, spreads wider, and a single news item can gap a stock dramatically. The page links each symbol to its research page and the scanner so you can check volume and trend before considering a move; the Learn hub explains position sizing to keep these larger swings controlled.",
"The list is an automatic, moment-in-time snapshot from public data — not a shopping list and not advice. Small-cap trading carries elevated risk of permanent loss. Verify quotes, liquidity and your own risk capacity before any trade."
],
"stocks/top-performers.html": [
"Top Performers shows which tracked stocks have gained the most today, sorted by percent change. It is the simplest expression of the day's strength and a natural first place to look for momentum — every strong move starts somewhere, and this page shows exactly where.",
"The most useful way to read a leaders list is with context. Is the top performer moving on a real catalyst (an announcement, a sector move) or is it a low-liquidity name ticking up on thin volume? Is the whole list green (broad strength) or are a handful of names doing all the work (narrow)? Answering those questions converts a list of numbers into a market read.",
"From here, the natural next step is the individual stock's research page to examine trend, support/resistance and volume, and the news feed for the reason behind the move. The scanner gives the same screening power with more filters if you want to define 'strong' more strictly.",
"The ranking is generated automatically from public data at load time and may be delayed; a strong day-one doesn't predict day-two, and chasing already-extended names is a common way to lose. Use the list for research, verify data, and apply your own discipline."
],
"stocks/undervalued.html": [
"The Undervalued page highlights tracked stocks trading at the lower end of their recent price range — the classic starting point for value-oriented research. It flags names where the price sits well below the year's highs and close to the lows, leaving room for mean-reversion or long-term value theses to be tested.",
"Cheapness is not automatically a reason to buy. A stock can be near its lows because the market is discounting real trouble — falling earnings, regulatory risk, sector rot. The page is designed to feed a *process*: see which names are out of favour, then investigate why, using the stock research page, the news feed covering corporate actions and announcements, and the fundamentals view when available.",
"Value investing rewards patience and research; mean-reversion trading rewards timing and risk control. This page supplies candidates for both, but the edge comes from the work you put in afterward — catalysts, margin of safety, and position size consistent with the risk.",
"This is an automatically generated screen from public price data, not a recommendation and not a promise that anything 'cheap' will recover. Value traps are real and short sellers exist for a reason. Verify fundamentals and exercise your own judgment before deciding."
],
"tools/position-size.html": [
"The position-size calculator turns risk decisions into concrete numbers: how many lots or shares fit your account given an entry, stop-loss and maximum acceptable loss. It is deliberately simple because the discipline it enforces — deciding what you will lose *before* you enter — is what separates professionals from gamblers.",
"Using it is easy: enter account size, the risk you are willing to take on the trade, entry and stop levels, and the tool shows position size and lot count. The habit it builds is the real value: if a stop distance or position size makes the required risk exceed your rules, the correct answer is often 'no trade' rather than a bigger account.",
"The calculator works for equities, futures and options (with penalty and margin awareness for options). It pairs naturally with the strategy builder for the payoff profile and with the Learn hub for how R:R and position sizing work in practice.",
"This is an educational tool, not financial advice. Brokers apply their own margins, penalties and lot rules; fees and slippage are real. Always size positions within what you can genuinely afford to lose, and never treat the tool's output as a guarantee."
]
}